version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: vote_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: vote_db
      MYSQL_USER: vote_user
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - /data/mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - vote_network

  redis:
    image: redis:6.2
    container_name: vote_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /data/redis:/data
    networks:
      - vote_network

networks:
  vote_network:
    driver: bridge

volumes:
  mysql_data:
  redis_data: 